# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

In [2]:
arr = np.linspace(0, 20, 28).reshape(4, 7)
arr

array([[ 0.        ,  0.74074074,  1.48148148,  2.22222222,  2.96296296,
         3.7037037 ,  4.44444444],
       [ 5.18518519,  5.92592593,  6.66666667,  7.40740741,  8.14814815,
         8.88888889,  9.62962963],
       [10.37037037, 11.11111111, 11.85185185, 12.59259259, 13.33333333,
        14.07407407, 14.81481481],
       [15.55555556, 16.2962963 , 17.03703704, 17.77777778, 18.51851852,
        19.25925926, 20.        ]])

In [3]:
arr = np.random.uniform(0, 20, (4, 7))
arr

array([[ 1.72405521, 13.73312353,  4.78182221, 15.2309712 ,  0.78845389,
        13.78823582, 15.9459525 ],
       [ 8.07168322, 17.40164848, 18.91500744,  3.20482365, 10.92508037,
         7.69050697,  6.02364946],
       [15.23853548,  6.2612728 ,  8.84589157,  2.20264751, 16.08485183,
        17.22438178, 10.86621167],
       [ 4.55419193,  9.13576068,  7.89134857,  6.91952138,  6.54518905,
        10.02120505,  8.71957987]])

In [4]:
mx = np.max(arr)
mn = np.min(arr)
arr = (arr - mn)/(mx - mn)
mx, mn, arr

(18.915007435115875,
 0.7884538924639717,
 array([[0.05161496, 0.71412746, 0.22030489, 0.79676025, 0.        ,
         0.71716788, 0.83620411],
        [0.4017989 , 0.91651149, 1.        , 0.13330553, 0.55921422,
         0.38077029, 0.28881362],
        [0.79717755, 0.30192275, 0.44451019, 0.07801779, 0.84386687,
         0.9067321 , 0.55596657],
        [0.20774705, 0.46050159, 0.39185026, 0.3382368 , 0.31758575,
         0.50934951, 0.43754186]]))

Нормализация вида ax+b

In [5]:
mx = np.max(arr)
mn = np.min(arr)

a = 1/(mx-mn)
b = -a*mn
print(a, b)

nr_arr = a*arr+b
nr_arr

1.0 -0.0


array([[0.05161496, 0.71412746, 0.22030489, 0.79676025, 0.        ,
        0.71716788, 0.83620411],
       [0.4017989 , 0.91651149, 1.        , 0.13330553, 0.55921422,
        0.38077029, 0.28881362],
       [0.79717755, 0.30192275, 0.44451019, 0.07801779, 0.84386687,
        0.9067321 , 0.55596657],
       [0.20774705, 0.46050159, 0.39185026, 0.3382368 , 0.31758575,
        0.50934951, 0.43754186]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [6]:
rnd_arr = np.random.randint(0, 10, size=(8, 10))
sum_lines = np.sum(rnd_arr, axis=1)
i = np.where(sum_lines == min(sum_lines))

rnd_arr, sum_lines, min(sum_lines), i, rnd_arr[i]

(array([[3, 5, 8, 0, 0, 6, 5, 8, 2, 2],
        [8, 3, 9, 5, 3, 2, 6, 4, 2, 1],
        [6, 7, 9, 7, 8, 8, 7, 4, 9, 9],
        [1, 4, 3, 1, 0, 2, 2, 3, 2, 1],
        [2, 7, 8, 3, 9, 9, 5, 6, 9, 3],
        [2, 1, 9, 5, 8, 4, 2, 2, 0, 2],
        [3, 6, 2, 8, 7, 4, 5, 9, 0, 2],
        [6, 4, 0, 8, 6, 1, 1, 4, 3, 6]]),
 array([39, 43, 74, 19, 61, 35, 46, 39]),
 19,
 (array([3], dtype=int64),),
 array([[1, 4, 3, 1, 0, 2, 2, 3, 2, 1]]))

In [7]:
rnd_arr = np.random.randint(0, 10, size=(8, 10))
i = np.where(np.sum(rnd_arr, axis=1) == min(np.sum(rnd_arr, axis=1)))
rnd_arr, rnd_arr[i], i

(array([[2, 4, 6, 2, 4, 1, 7, 2, 4, 8],
        [5, 0, 6, 1, 9, 7, 7, 5, 2, 9],
        [4, 5, 3, 4, 3, 2, 2, 0, 7, 4],
        [3, 4, 2, 3, 6, 8, 5, 9, 7, 2],
        [6, 0, 7, 7, 5, 1, 6, 0, 7, 8],
        [1, 1, 9, 1, 3, 9, 2, 2, 2, 1],
        [5, 6, 6, 2, 6, 1, 2, 6, 0, 5],
        [6, 4, 4, 8, 5, 9, 1, 2, 5, 4]]),
 array([[1, 1, 9, 1, 3, 9, 2, 2, 2, 1]]),
 (array([5], dtype=int64),))

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [8]:
a = np.array([0, 0, 0, 13])
b = np.array([6, 4, 0, 2])
sum((a-b)**2)**0.5

13.152946437965905

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [9]:
A = np.matrix(
    [[-1, 2, 4], 
     [-3, 1, 2], 
     [-3, 0, 1]])

B = np.matrix(
    [[3, -1], 
     [2, 1]])

C = np.matrix(
    [[7, 21], 
     [11, 8], 
     [8, 4]])

x = np.linalg.inv(A)*(-C)*np.linalg.inv(B)
x

matrix([[ 1.00000000e+00,  1.11022302e-15],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

In [10]:
-np.linalg.inv(A).dot(C).dot(np.linalg.inv(B))

matrix([[ 1.00000000e+00,  1.11022302e-15],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [36]:
data = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1)
data

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [12]:
for i in range(1, data.shape[1]):
    print(f'#{i}: min = {data[:, i].min()} max = {data[:, i].max()}, mean = {data[:, i].mean()}, median = {np.median(data[:, i])}')

#1: min = 0 max = 2147483647, mean = 21601.00169, median = 40.0
#2: min = 1 max = 39, mean = 9.05528, median = 9.0


In [13]:
data.shape

(100000, 3)

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [37]:
quantile_75 = np.quantile(data[:, 1], 0.75)
print(quantile_75)
data[:, 1] = np.where(data[:, 1] > quantile_75, quantile_75, data[:, 1])
data

65.0


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [42]:
print(np.count_nonzero(data[:, 1] == 0))
data[:, 1] = np.where(data[:, 1] != 0, data[:, 1], 1)
data

479


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [38]:
len(np.unique(data[:, 1:3])) # Искал разные ID, так как не понятно, что такое разные рецепты

66

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [17]:
len(np.unique(data[:, 2])), np.unique(data[:, 2])

(37,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39]))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [18]:
short_cut = data[np.where(data[:, 2] <= 5)[0]]
short_cut, short_cut.shape

(array([[446597,     15,      5],
        [204134,      5,      3],
        [ 25623,      6,      4],
        ...,
        [ 52088,     60,      5],
        [128811,     15,      4],
        [370915,      5,      4]]),
 (17262, 3))

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [43]:
np.max(data[:, 2]/data[:, 1]), data[:, 2]/data[:, 1]

(24.0,
 array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
        0.21538462]))

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [20]:
sorted_indices = np.argsort(data[:, 1])[-100:]
sorted_array = data[sorted_indices]
sorted_array[:, 2].mean()

9.96

In [21]:
# Сортировка рецептов по продолжительности выполнения
sorted_data = data[data[:, 1].argsort()[::-1]]

# Выбор топ-100 рецептов с наибольшей продолжительностью
top_100_recipes = sorted_data[:100]

# Вычисление среднего количества ингредиентов для топ-100 рецептов
mean_ingredients_top_100 = np.mean(top_100_recipes[:, 2])

# Вывод результата
print("Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью:", mean_ingredients_top_100)

Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью: 9.96


In [44]:
sorted_data9 = data[data[:, 1].argsort()[::-1]]
top_100_recipes = sorted_data9[:100]
avg_ingredients = np.average(top_100_recipes[:, 2])
print("Среднее количество ингредиентов для топ-100 рецептов:", avg_ingredients)

Среднее количество ингредиентов для топ-100 рецептов: 9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [22]:
idx = np.random.randint(data.shape[0], size=10)
data[idx, :]

array([[105492,     20,     13],
       [ 32271,     40,      7],
       [151557,     65,     12],
       [ 80108,     17,     12],
       [413018,     65,     10],
       [369796,     10,      7],
       [ 54336,     42,     12],
       [302141,     20,      6],
       [200101,     20,      6],
       [136594,     55,      9]])

In [45]:
random_indices = np.random.choice(len(data), size=10, replace=False)

random_recipes = data[random_indices]

print("Информация о случайно выбранных рецептах:")
print(random_recipes)

Информация о случайно выбранных рецептах:
[[ 65717     13     12]
 [ 25800     65     11]
 [ 55040     30     13]
 [ 56215     65      6]
 [230140     10      4]
 [140335     65      8]
 [503386     40     10]
 [141982     25     13]
 [212375     65     16]
 [296337     60     11]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [23]:
str(len(np.where(data[:, 2] < data[:, 2].mean())[0])/data.shape[0]*100) + "%"

'58.802%'

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [46]:
good_recepts = np.zeros((data.shape[0], 4), dtype=int)
good_recepts[:, :3] = data
good_recepts[np.where((data[:, 2] <= 5) & (data[:, 1] <= 20)), 3] = 1
good_recepts

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [32]:
str(sum(good_recepts[:, 3])/data.shape[0]*100) + '%'

'9.552%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [26]:
short_recipes = data[data[:, 1] < 10]
standard_recipes = data[(data[:, 1] >= 10) & (data[:, 1] < 20)]
long_recipes = data[data[:, 1] >= 20]

max_length = min(len(short_recipes), len(standard_recipes), len(long_recipes))

three_dimensional_array = np.zeros((3, max_length, 3), dtype=int)

three_dimensional_array[0, :max_length, :] = short_recipes[:max_length]
three_dimensional_array[1, :max_length, :] = standard_recipes[:max_length]
three_dimensional_array[2, :max_length, :] = long_recipes[:max_length]

three_dimensional_array.shape, three_dimensional_array

((3, 7588, 3),
 array([[[ 67660,      5,      6],
         [366174,      7,      9],
         [204134,      5,      3],
         ...,
         [420725,      5,      3],
         [  4747,      1,      9],
         [370915,      5,      4]],
 
        [[ 94746,     10,      6],
         [ 33941,     18,      9],
         [446597,     15,      5],
         ...,
         [  9831,     15,      7],
         [335859,     12,     14],
         [256812,     10,      3]],
 
        [[127244,     60,     16],
         [ 23891,     25,      7],
         [157911,     60,     14],
         ...,
         [168901,     25,      7],
         [392339,     35,     13],
         [206732,     45,     10]]]))